#!/usr/bin/env python3
#
# Copyright (c) 2016-2018, Neil Booth
#
# All rights reserved.
#
# See the file "LICENCE" for information about the copyright
# and warranty status of this software.

'''Script to kick off the server.'''

import logging
import sys
import traceback
import os

from electrumx import Controller, Env
from electrumx.lib.util import CompactFormatter, make_logger


def main():
    '''Set up logging and run the server.'''
    env = Env()
    log_fmt = Env.default('LOG_FORMAT', '%(asctime)s:%(levelname)s:%(name)s:%(message)s')
    handler1 = logging.StreamHandler(sys.stdout)
    handler1.setFormatter(CompactFormatter(log_fmt))
    handler2 = logging.FileHandler(os.path.join(env.db_dir, "logfile"))
    handler2.setFormatter(CompactFormatter(log_fmt))
    make_logger('electrumx', handlers=[handler1, handler2], level=logging.INFO)

    logging.info('ElectrumX server starting')
    try:
        controller = Controller(env)
        controller.run()
    except Exception:
        traceback.print_exc()
        logging.critical('ElectrumX server terminated abnormally')
    else:
        logging.info('ElectrumX server terminated normally')


if __name__ == '__main__':
    main()
